TYPO3:
  Flow:
    i18n:
      defaultLocale: de
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes: [ 404 ]
            options:
              templatePathAndFilename: 'resource://Hfrahmann.Website/Private/Templates/Error/Index.html'
              format: 'html'
